apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        env:
        - name: APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: guestbook-secret
              key: token
        command:
          - "curl"
          - "-d"
          - "text=App Sync Succeeded!"
          - "-d"
          - "channel=argocd"
          - "-H"
          - "Authorization: Bearer $(APP_TOKEN)"
          - "-X"
          - "POST"
          - "https://slack.com/api/chat.postMessage"
      restartPolicy: Never
  backoffLimit: 2
