apiVersion: v1
kind: Secret
metadata:
  name: guestbook-secret
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  token: eG94Yi0yNDYwMjY1OTQwMzM3LTI0NDc2NTUyNTEyNTEtWUJqM0hHR3NnVHJqR3FTdmppMVU0ZFEx
